backend:
  name: git-gateway
  branch: main
media_folder: "assets/images"
public_folder: "/assets/images"
collections:
  - name: "hero"
    label: "Герой-секция"
    folder: "_hero"
    create: true
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Подзаголовок", name: "subtitle", widget: "string" }
      - { label: "Текст", name: "text", widget: "text" }
      - { label: "Изображение", name: "image", widget: "image" }
  - name: "manifest"
    label: "Манифест"
    folder: "_manifest"
    create: true
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Принципы", name: "principles", widget: "list" }
  - name: "services"
    label: "Услуги"
    folder: "_services"
    create: true
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Услуги", name: "items", widget: "list", fields: [
          { label: "Название", name: "name", widget: "string" },
          { label: "Описание", name: "description", widget: "text" }
        ]}
  - name: "cases"
    label: "Кейсы"
    folder: "_cases"
    create: true
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Кейсы", name: "items", widget: "list", fields: [
          { label: "Название", name: "name", widget: "string" },
          { label: "Описание", name: "description", widget: "text" },
          { label: "Изображ